### ISSUE TITLE
Fails with rollup and uglify

### ISSUE THREAD

**Issue by polandj** [coussej/svelte-app-router#1]
Hi by simply installing the npm and including 

    import Router from 'svelte-app-router';

In my component, it then fails to build with the following error:

    [!] (uglify plugin) Error: Error transforming bundle with 'uglify' plugin: Unexpected token: punc (,)
    Error: Error transforming bundle with 'uglify' plugin: Unexpected token: punc (,)
      at error (/Users/jp/Documents/Arduino/libraries/KGB/node_modules/rollup/dist/rollup.js:185:14)
      at Promise.resolve.then.then.catch.err 
    (/Users/jp/Documents/Arduino/libraries/KGB/node_modules/rollup/dist/rollup.js:9482:5)

Here's the NPM info:

    "babel-core": "^6.26.0",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-preset-env": "^1.6.1",
    "lodash": "^4.17.4",
    "rollup": "^0.50.0",
    "rollup-plugin-babel": "^3.0.2",
    "rollup-plugin-commonjs": "^8.2.1",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-plugin-svelte": "^3.1.0",
    "rollup-plugin-uglify": "^2.0.1",
    "rollup-watch": "^4.3.1",
    "svelte": "^1.40.2",
    "svelte-cli": "^1.4.0",
    "uglify-js": "^3.1.3",
    "zepto": "^1.2.0"

**Comment by coussej** [comment]
Looks like uglify suggests there is a syntax error in the code somewhere, but as it passes the StandardJS linter I'm quite sure the code is ok. Do you parse with babel before uglifying, because it is written with some ES6 syntax? 

Can you try to locate on which part of the source it fails? Or even better, point me to a repository where I can try building myself?

**Comment by polandj** [comment]
SO, here’s the weird thing: if I use Router.html directly, it works fine.  I presume it is a ES6/babel thing, as I explicitly don’t pass noe modules thru babel.  In any case, it seems the easiest thing to do, since this is small and simple, is use Router.html directly and call it a day.  (feel free to close issue, or I will if you want)

Thanks!

- JP

**Comment by coussej** [comment]
Ok, thanks for the feedback!
